// GLSL Vertex Shader "VS2"
// Generated by XShaderCompiler
// 22/01/2017 17:39:29

#version 140

in vec4 vPos;

layout(std140) uniform Matrices
{
    mat4 wvpMatrix;
    mat4 wMatrix;
};

void f1(inout vec4 v)
{
    v.x += 1.0;
}

void main()
{
    f1(vPos);
    gl_Position = (wvpMatrix * vPos);
}

