// GLSL Vertex Shader "VS2"
// Generated by XShaderCompiler
// 22/01/2017 17:39:29

#version 150

in vec4 vPos;

layout(std140) uniform Matrices
{
    mat4 wvpMatrix;
    mat4 wMatrix;
};

struct VOut
{
    vec3 color1;
    vec3 color2;
};

out xsc_VOut
{
    VOut outp;
};

void main()
{
    outp.color1 = vec3(1);
    outp.color2 = vec3(2);
    gl_Position = (wvpMatrix * vPos);
}

